version: '3'
services:
  workbench:
    build: ./workbench
    ports:
    - "8080:8080"
  virtue-admin:
    build:
        context: ../../../
        dockerfile: modules/docker/server-images/virtue-admin/Dockerfile
