version: '3'
services:
  workbench:
    volumes: /var/run/docker.sock:/var/run/docker.sock
    build: 
        context: ./workbench
    ports:
    - "8080:8080"
  virtue-admin:
    volumes: 
    - ./modules/virtue-admin/database:/opt/virtue/virtue-admin/build/distributions/virtue-admin-0.0.1-SNAPSHOT/database
    - /var/run/docker.sock:/var/run/docker.sock
    build:
        context: ../../../
        dockerfile: modules/docker/server-images/virtue-admin/Dockerfile
